AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pet Store Rest API Service
Resources:
  PetStoreApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: s3://pet-store-api-deployment-workspace-binu1/6dd76c60702778fceea16229464010f2
  PostPetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostPetFunction
      Runtime: python3.6
      Handler: function.handler
      CodeUri: s3://pet-store-api-deployment-workspace-binu1/b034c3340e83240168c4d10f68fae73a
      Events:
        PostPetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: PetStoreApiGateway
            Path: /pet
            Method: POST
      Policies:
      - AWSLambdaBasicExecutionRole
  GetPetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetPetFunction
      Runtime: python3.6
      Handler: function.handler
      CodeUri: s3://pet-store-api-deployment-workspace-binu1/b034c3340e83240168c4d10f68fae73a
      Events:
        GetPetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: PetStoreApiGateway
            Path: /pet/{petId}
            Method: GET
      Policies:
      - AWSLambdaBasicExecutionRole
